services:
  db:
    image: postgres:17
    container_name: hype-postgres
    environment:
      POSTGRES_USER: hype
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: hype
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hype -d hype"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: